# -*- coding: utf-8 -*-
"""PySpark-Training-LoadData-DataFrame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VRvZMhteWBtwjLGQ3mRpBUucUUv3faCw
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()
spark

df = spark.read.format("csv").option("header","true").load("original.csv")
df.show()

df2 = spark.read.csv("original.csv", header=True)
df2.show()

df2.dtypes

from pyspark.sql.types import *
schema = StructType([
 StructField('id', IntegerType()),
 StructField('first_name', StringType()),
 StructField('last_name', StringType()),
 StructField('gender', StringType()),
 StructField('City', StringType()),
 StructField('JobTitle', StringType()),
 StructField('Salary', StringType()),
 StructField('Latitude', StringType()),
 StructField('Longitude', FloatType())
])

df3 = spark.read.csv("original.csv", header=True, schema=schema)
df3.show()

df3.dtypes

